  config:
      nvidia_drivers:
        enable: true
        prefer_open_drivers: false
      amd_drivers: true
      intel_drivers: true
      kanata: true
      zram: true
      limine:
        snapper_sync: true
        journalctl_desktop_notification: false
      gaming: true
      vm:
        # Guest machine needs the following packages: qemu-guest-agent spice-vdagent
        qemu: true
        # For virt_manager qemu also needs to be enabled
        virt_manager: true
        # For quickemu qemu also needs to be enabled
        quickemu: false
