  config:
      # Add CachyOS repositories
      # CachyOS is an Arch-based distribution that compiles packages
      # with optimizations specific to modern x86_64 CPU
      # microarchitectures. To quote, they offer "5%-20% performance
      # uplift compared to x86-64." Check the CPU compatibility table
      # to help decide whether to enable this configuration:
      # https://wiki.cachyos.org/installation/installation_prepare/#x86_64-microarchitecture-level-support
      cachyos_repos: false
      nvidia_drivers:
        enable: false
        prefer_open_drivers: false
      amd_drivers: true
      intel_drivers: false
      multilib: true
      ui_environment:
        hyprland: true
      kanata: true
      zram: true
      limine:
        snapper_sync: true
        journalctl_desktop_notification: false
      gaming: true
      wallpaper:
        color_mode: "dark"
      qemu:
        # Install packages for QEMU
        enable: false
        # Virt Manager is a frontend for KVM/QEMU
        virt_manager: false
      extra_fonts: true # Install extra fonts as specified in the config `font_packages`
      flatpak: false # Also includes Flatseal
      shell:
        enable: true
        repo: "dianaw353/Lunur-Shell"
        install_script_file_path: "install_requirements.sh"
      school: true # install packages for school
