  config:
      nvidia_drivers:
        enable: true
        prefer_open_drivers: false
      amd_drivers: true
      intel_drivers: true
      kanata: true
      zram: true
      limine:
        snapper_sync: true
