  config:
      nvidia_drivers:
        enable: true
        prefer_open_drivers: false
      amd_drivers: true
      intel_drivers: true
      ui-environment:
        hyprland: true
      kanata: true
      zram: true
      limine:
        snapper_sync: true
        journalctl_desktop_notification: false
      gaming: true
      wallpaper:
        color_mode: "dark"
      qemu:
        # Install packages for QEMU
        enable: true
        # Virt Manager is a frontend for KVM/QEMU
        virt_manager: true
      shell:
        enable: true
        repo: "dianaw353/Lunur-Shell"
        install_script_file_path: "install_requirements.sh"
