services:
  system:
    bluetooth:
      - bluetooth
    printing:
      - cups
    login_manager:
      ly:
        - ly@tty2
    gaming:
      - gamemoded
  user:
    audio:
      pipewire:
        - pipewire
        - wireplumber

kvm_services:
  system:
    - libvirtd 

