theme= "base16_transparent"
# theme= "base16_transparent"
theme = "matugen"

[editor]
mouse = false
bufferline = "always"
true-color = true
color-modes = true
popup-border = "all"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
